

from plant.model import (Address as a, 
                         Activity as act,
                         BatchHistory as er2,
                         BatchItem as bi,
                         Calendar as cal, 
                         CoverColor as cc, 
                         CoverMaterial as cm, 
                         Country as c, 
                         Currency as cur, 
                         Customer as cus, 
                         Email as e, 
                         ErrorReport as err,
                         ExchangeRate as er,
                         GCReport as gcr,
                         Location as lv,
                         Invoice2 as i, 
                         Order as o, 
                         OrderComment as oc, 
                         OrderDiscount as od, 
                         OrderItem as oi, 
                         OrderItemComment as oic,
                         OrderItemFeature as oif, 
                         OrderItemHistory as can,   # cancel history record
                         Partner as par, 
                         Payment as pay, 
                         ProductCoverType as pct, 
                         Product as p, 
                         ProductItem as pi, 
                         ProductType as pt, 
                         PressRouting as pr, 
                         Promotion as pro, 
                         Rework as r, 
                         ReworkReason as rr, 
                         ShippingMethod as sm,
                         SoftwareClient as sc, 
                         SoftwareVersion as sv, 
                         State as s,
                         Theme as t, 
                         UriResource as dwn,
                         User as cu,                # canceller
                         WorkflowItem as wi)
